# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: containerd-kms-crypt
spec:
  selector:
    app: containerd-kms-crypt
  type: ClusterIP
  ports:
    - name: containerd-kms-crypt
      protocol: TCP
      port: 80
      targetPort: 9666
---

